### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by kichooo** [VoltDB/voltdb-client-nodejs#15]
Hello, 

version in package.json shows 0.2, while when I go to downloads page of volt db, nodejs driver is version 1.1. 

Does that mean that this repository is not longer maintained, or just versioning is different?

Can I use this driver in application or is it not encouraged?

**Comment by benjaminballard** [comment]
Hi,

This driver is still maintained, but we are not currently developing features for it.  You are right, the version in package.json does not reflect the latest release version numbering, I will update that.

We do encourage this driver for node.js applications.  It is one of the most performant drivers.  We did a few blogs about it, including a benchmark that ran upwards of 600K transactions per second.

https://voltdb.com/blog/new-and-improved-nodejs-driver-voltdb
https://voltdb.com/blog/695k-tps-nodejs-and-voltdb
https://voltdb.com/blog/using-nodejs-voltdb

What sort of application are you building?  Are you in touch with one of our Sales Engineers for assistance?  If you'd like to get in touch with one, you can email sales@voltdb.com and someone will contact you.  Or, if you are a customer already you can contact support@voltdb.com for assistance.

Best regards,
Ben

**Comment by DodiChen** [comment]
Hi,
the link https://voltdb.com/blog/new-and-improved-nodejs-driver-voltdb and https://voltdb.com/blog/using-nodejs-voltdb are invalid.
Could you please provide me the valid links.
Thanks.
Best regards,
Dodi

**Comment by jpiekos** [comment]
We've got a new website up and will be fixing the blog links shortly.  We'll post an update here when those 2 are available.

John

**Comment by jpiekos** [comment]
Those links now work Dodi, sorry for the inconvenience.

John
